PROJECTILE_SPELLS = {
    ["Fizz"]                      = {Spellname ="FizzMarinerDoom",Name = "Fizz", Spellslot =_R},
    ["Aatrox"]                      = {Spellname ="AatroxE",Name= "Aatrox", Spellslot =_E},
    ["Ahri"]                      = {Spellname ="AhriOrbofDeception",Name = "Ahri", Spellslot =_Q},
    ["Ahri2"]                      = {Spellname ="AhriFoxFire",Name = "Ahri", Spellslot =_W},
    ["Ahri3"]                      = {Spellname ="AhriSeduce",Name = "Ahri", Spellslot =_E},
    ["Ahri3"]                      = {Spellname ="AhriTumble",Name = "Ahri", Spellslot =_R},
    ["Anivia"]                      = {Spellname ="FlashFrost",Name = "Anivia", Spellslot =_Q},
    ["Anivia2"]                      = {Spellname ="Frostbite",Name = "Anivia", Spellslot =_E},
    ["Annie"]                      = {Spellname ="Disintegrate",Name = "Annie", Spellslot =_Q},
    ["Ashe"]                      = {Spellname ="Volley",Name ="Ashe", Spellslot =_W},
    ["Ashe2"]                      = {Spellname ="EnchantedCrystalArrow",Name ="Ashe", Spellslot =_R},
    ["Amumu"]                      = {Spellname ="BandageToss",Name ="Amumu",Spellslot =_Q},
    ["Blitzcrank"]                      = {Spellname ="RocketGrabMissile",Name ="Blitzcrank",Spellslot =_Q},
    ["Brand"]                      = {Spellname ="BrandBlaze",Name ="Brand", Spellslot =_Q},
    ["Brand2"]                      = {Spellname ="BrandWildfire",Name ="Brand", Spellslot =_R},
    ["Braum"]                      = {Spellname ="BraumQ",Name ="Braum",Spellslot =_Q},
    ["Braum2"]                      = {Spellname ="BraumRWapper",Name ="Braum",Spellslot =_R},
    ["Caitlyn"]                      = {Spellname ="CaitlynPiltoverPeacemaker",Name ="Caitlyn",Spellslot =_Q},
    ["Caitlyn2"]                      = {Spellname ="CaitlynEntrapment",Name ="Caitlyn",Spellslot =_E},
    ["Caitlyn3"]                      = {Spellname ="CaitlynAceintheHole",Name ="Caitlyn",Spellslot =_R},
    ["Cassiopiea"]                      = {Spellname ="CassiopeiaMiasma",Name ="Cassiopiea",Spellslot =_W},
    ["Cassiopiea2"]                      = {Spellname ="CassiopeiaTwinFang",Name ="Cassiopiea",Spellslot =_E},
    ["Corki"]                      = {Spellname ="PhosphorusBomb",Name ="Corki",Spellslot =_Q},
    ["Corki2"]                      = {Spellname ="MissileBarrage",Name ="Corki",Spellslot =_R},
    ["Diana"]                      = {Spellname ="DianaArc",Name ="Diana",Spellslot =_Q},
    ["DrMundo"]                      = {Spellname ="InfectedCleaverMissileCast",Name ="DrMundo",Spellslot =_Q},
    ["Draven"]                      = {Spellname ="dravenspinning",Name ="Draven",Spellslot =_Q},
    ["Draven2"]                      = {Spellname ="DravenDoubleShot",Name ="Draven",Spellslot =_E},
    ["Draven3"]                      = {Spellname ="DravenRCast",Name ="Draven",Spellslot =_R},
    ["Elise"]                      = {Spellname ="EliseHumanQ",Name ="Elise",Spellslot =_Q},
    ["Elise2"]                      = {Spellname ="EliseHumanE",Name ="Elise",Spellslot =_E},
    ["Evelynn"]                      = {Spellname ="EvelynnQ",Name ="Evelynn",Spellslot =_Q},
    ["Ezreal"]                      = {Spellname ="EzrealMysticShot",Name ="Ezreal",Spellslot =_Q,},
    ["Ezreal2"]                      = {Spellname ="EzrealEssenceFlux",Name ="Ezreal",Spellslot =_W},
    ["Ezreal3"]                      = {Spellname ="EzrealArcaneShift",Name ="Ezreal",Spellslot =_R},
    ["Galio"]                      = {Spellname ="GalioRighteousGust",Name ="Galio",Spellslot =_E},
    ["Galio2"]                      = {Spellname ="GalioResoluteSmite",Name ="Galio",Spellslot =_Q},
    ["Gangplank"]                      = {Spellname ="Parley",Name ="Gangplank",Spellslot =_Q},
    ["Gnar"]                      = {Spellname ="GnarQ",Name ="Gnar",Spellslot =_Q},
    ["Graves"]                      = {Spellname ="GravesClusterShot",Name ="Graves",Spellslot =_Q},
    ["Graves2"]                      = {Spellname ="GravesChargeShot",Name ="Graves",Spellslot =_R},
    ["Heimerdinger"]                      = {Spellname ="HeimerdingerW",Name ="Heimerdinger",Spellslot =_W},
    ["Irelia"]                      = {Spellname ="IreliaTranscendentBlades",Name ="Irelia",Spellslot =_R},
    ["Janna"]                      = {Spellname ="HowlingGale",Name ="Janna",Spellslot =_Q},
    ["Jayce"]                      = {Spellname ="JayceToTheSkies" or "jayceshockblast",Name ="Jayce",Spellslot =_Q},
    ["Jinx"]                      = {Spellname ="JinxW",Name ="Jinx",Spellslot =_W},
    ["Jinx2"]                      = {Spellname ="JinxR",Name ="Jinx",Spellslot =_R},
    ["Kalista"]                      = {Spellname ="KalistaMysticShot",Name ="Kalista",Spellslot =_Q},
    ["Karma"]                      = {Spellname ="KarmaQ",Name ="Karma",Spellslot =_Q},
    ["Kassidan"]                      = {Spellname ="NullLance",Name ="Kassidan",Spellslot =_Q},
    ["Katarina"]                      = {Spellname ="KatarinaR",Name ="Katarina",Spellslot =_R},
    ["Leblanc"]                      = {Spellname ="LeblancChaosOrb",Name ="Leblanc",Spellslot =_Q},
    ["Leblanc2"]                      = {Spellname ="LeblancSoulShackle" or "LeblancSoulShackleM",Name ="Leblanc",Spellslot =_E},
    ["Leesin"]                      = {Spellname ="BlindMonkQOne",Name ="Leesin",Spellslot =_Q},
    ["Leona"]                      = {Spellname ="LeonaZenithBladeMissle",Name ="Leona",Spellslot =_E},
    ["Lissandra"]                      = {Spellname ="LissandraE",Name ="Lissandra",Spellslot =_E},
    ["Lucian"]                      = {Spellname ="LucianR",Name ="Lucian",Spellslot =_R}, 
    ["Lux"]                      = {Spellname ="LuxLightBinding",Name ="Lux",Spellslot =_Q},
    ["Lux2"]                      = {Spellname ="LuxLightStrikeKugel",Name ="Lux",Spellslot =_E},
    ["Missfortune"]                      = {Spellname ="MissFortuneBulletTime",Name ="Missfortune",Spellslot =_R},
    ["Morgana"]                      = {Spellname ="DarkBindingMissile",Name ="Morgana",Spellslot =_Q},
    ["Nami"]                      = {Spellname ="NamiR",Name ="Nami",Spellslot =_R},
    ["Nidalee"]                      = {Spellname ="JavelinToss",Name ="Nidalee",Spellslot =_Q},
    ["Nocturne"]                      = {Spellname ="NocturneDuskbringer",Name ="Nocturne",Spellslot =_Q},
    ["Pantheon"]                      = {Spellname ="Pantheon_Throw",Name ="Pantheon",Spellslot =_Q},
    ["Quinn"]                      = {Spellname ="QuinnQ",Name ="Quinn",Spellslot =_Q},
    ["Rengar"]                      = {Spellname ="RengarE",Name ="Rengar",Spellslot =_E},
    ["Riven"]                      = {Spellname ="rivenizunablade",Name ="Riven",Spellslot =_R},
    ["Ryze"]                      = {Spellname ="Overload",Name ="Ryze",Spellslot =_Q},
    ["Ryze2"]                      = {Spellname ="SpellFlux",Name ="Ryze",Spellslot =_E},
    ["Sejuani"]                      = {Spellname ="SejuaniGlacialPrisonStart",Name ="Sejuani",Spellslot =_R},
    ["Sivir"]                      = {Spellname ="SivirQ",Name ="Sivir",Spellslot =_Q},
    ["Sivir2"]                      = {Spellname ="SivirE",Name ="Sivir",Spellslot =_E},
    ["Skarner"]                      = {Spellname ="SkarnerFractureMissileSpell",Name ="Skarner",Spellslot =_E},
    ["Sona"]                      = {Spellname ="SonaCrescendo",Name ="Sona",Spellslot =_R},
    ["Swain"]                      = {Spellname ="SwainDecrepify",Name ="Swain",Spellslot =_Q},
    ["Swain2"]                      = {Spellname ="SwainMetamorphism",Name ="Swain",Spellslot =_R},
    ["Syndra"]                      = {Spellname ="SyndraE",Name ="Syndra",Spellslot =_E},
    ["Syndra2"]                      = {Spellname ="SyndraR",Name ="Syndra",Spellslot =_R},
    ["Talon"]                      = {Spellname ="TalonRake",Name ="Talon",Spellslot =_W},
    ["Talon2"]                      = {Spellname ="TalonShadowAssault",Name ="Talon",Spellslot =_R},
    ["Teemo"]                      = {Spellname ="BlindingDart",Name ="Teemo",Spellslot =_Q},
    ["Thresh"]                      = {Spellname ="ThreshQ",Name ="Thresh",Spellslot =_Q},
    ["Tristana"]                      = {Spellname ="BusterShot",Name ="Tristana",Spellslot =_R},
    ["Varus"]                      = {Spellname ="VarusQ",Name ="Varus",Spellslot =_Q},
    ["Varus2"]                      = {Spellname ="VarusR",Name ="Varus",Spellslot =_R},
    ["Vayne"]                      = {Spellname ="VayneCondemm",Name ="Vayne",Spellslot =_E},
    ["Veigar"]                      = {Spellname ="VeigarPrimordialBurst",Name ="Veigar",Spellslot =_R},
    ["Twistedfate"]                      = {Spellname ="WildCards",Name ="Twistedfate",Spellslot =_Q},
    ["Velkoz"]                      = {Spellname ="VelkozQ",Name ="Velkoz",Spellslot =_Q},
    ["Velkoz2"]                      = {Spellname ="VelkozW",Name ="Velkoz",Spellslot =_W},
    ["Viktor"]                      = {Spellname ="ViktorDeathRay",Name ="Viktor",Spellslot =_E},
    ["Xerath"]                      = {Spellname ="XerathArcanoPulseChargeUp",Name ="Xerath",Spellslot =_Q},
    ["Zed"]                      = {Spellname ="ZedShuriken",Name ="Zed",Spellslot =_Q},
    ["Ziggs"]                      = {Spellname ="ZiggsR",Name ="Ziggs",Spellslot =_R},
    ["Ziggs2"]                      = {Spellname ="ZiggsQ",Name ="Ziggs",Spellslot =_Q},
    ["Zyra"]                      = {Spellname ="ZyraGraspingRoots",Name ="Zyra",Spellslot =_E}
}
